/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Career.Resume;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;




/**
 *
 * @author sneha
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private Resume resume;
    public CreateJPanel(Resume resume) {
        initComponents();
        this.resume= resume;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        createJLabel = new javax.swing.JLabel();
        nameHeadingJLabel = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameJLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressLine1JLabel = new javax.swing.JLabel();
        addressLine1TextField = new javax.swing.JTextField();
        cityJLabel = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        addressLine2JLabel = new javax.swing.JLabel();
        addressLine2JTextField = new javax.swing.JTextField();
        countryJLabel = new javax.swing.JLabel();
        countryJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        affiliationJTextField = new javax.swing.JTextField();
        affiliationJLabel = new javax.swing.JLabel();
        objectiveStatementJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        educationHeadingJLabel = new javax.swing.JLabel();
        degree1JLabel = new javax.swing.JLabel();
        degree1JTextField = new javax.swing.JTextField();
        degree2JLabel = new javax.swing.JLabel();
        degree2JTextField = new javax.swing.JTextField();
        startDate1JLabel = new javax.swing.JLabel();
        start1JTextField = new javax.swing.JTextField();
        startDate2JLabel = new javax.swing.JLabel();
        startDate2JTextField = new javax.swing.JTextField();
        endDte1JLabel = new javax.swing.JLabel();
        endDate1JTextField = new javax.swing.JTextField();
        endDate2JLabel = new javax.swing.JLabel();
        endDate2JTextField = new javax.swing.JTextField();
        degree3JLabel = new javax.swing.JLabel();
        degree3JTextField = new javax.swing.JTextField();
        startDate3JLabel = new javax.swing.JLabel();
        startDate3JTextField = new javax.swing.JTextField();
        endDate3JLabel = new javax.swing.JLabel();
        endDate3JTextField = new javax.swing.JTextField();
        workExperienceJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        skillsJLabel = new javax.swing.JLabel();
        javaJCheckBox = new javax.swing.JCheckBox();
        webDesignJCheckBox = new javax.swing.JCheckBox();
        dotnetJCheckBox = new javax.swing.JCheckBox();
        databaseJCheckBox = new javax.swing.JCheckBox();
        bigDataJCheckBox = new javax.swing.JCheckBox();
        cJCheckBox = new javax.swing.JCheckBox();
        certificationsJLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        browseJButton = new javax.swing.JButton();
        ImageheadingJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        certifictionsJTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        objectiveJTextArea = new javax.swing.JTextArea();
        browsePathJTextField = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createJLabel.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        createJLabel.setText("Create Your Resume");
        add(createJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 28, -1, -1));

        nameHeadingJLabel.setText("Please Enter Your Name");
        add(nameHeadingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 133, -1, -1));

        firstNameJLabel.setText("First Name: ");
        add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 185, -1, -1));

        firstNameTextField.setText(" ");
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 182, 209, -1));

        lastNameJLabel.setText("Last Name:");
        add(lastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 185, -1, -1));

        lastNameTextField.setText(" ");
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 182, 216, -1));

        addressLabel.setText("Please Enter Your Address in the space provided below");
        add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 246, -1, -1));

        addressLine1JLabel.setText("Address Line 1:");
        add(addressLine1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 298, -1, -1));

        addressLine1TextField.setText(" ");
        addressLine1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine1TextFieldActionPerformed(evt);
            }
        });
        add(addressLine1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 295, 354, -1));

        cityJLabel.setText("City :");
        add(cityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 298, -1, -1));

        cityJTextField.setText(" ");
        add(cityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 295, 331, -1));

        addressLine2JLabel.setText("Address Line 2:");
        add(addressLine2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 353, -1, -1));

        addressLine2JTextField.setText(" ");
        add(addressLine2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 350, 354, -1));

        countryJLabel.setText("Country :");
        add(countryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 353, -1, -1));

        countryJTextField.setText(" ");
        add(countryJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 350, 331, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 407, 1240, 10));

        affiliationJTextField.setText(" ");
        add(affiliationJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 424, 369, -1));

        affiliationJLabel.setText("Affiliation :  ");
        add(affiliationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 427, -1, -1));

        objectiveStatementJLabel.setText("Career Objective Statement :");
        add(objectiveStatementJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 491, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 721, 1421, -1));

        educationHeadingJLabel.setText("Education Details : ");
        add(educationHeadingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 729, -1, -1));

        degree1JLabel.setText("Degree 1 : ");
        add(degree1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 789, -1, -1));

        degree1JTextField.setText(" ");
        degree1JTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                degree1JTextFieldKeyPressed(evt);
            }
        });
        add(degree1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 786, 227, -1));

        degree2JLabel.setText("Degree 2 : ");
        add(degree2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 844, -1, -1));
        add(degree2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 841, 227, -1));

        startDate1JLabel.setText("Start Date :");
        add(startDate1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 789, -1, -1));

        start1JTextField.setText(" ");
        add(start1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 786, 209, -1));

        startDate2JLabel.setText("Start Date :");
        add(startDate2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 844, -1, -1));

        startDate2JTextField.setText(" ");
        add(startDate2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 841, 209, -1));

        endDte1JLabel.setText(" End Date : ");
        add(endDte1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 789, -1, -1));

        endDate1JTextField.setText(" ");
        add(endDate1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1246, 786, 201, -1));

        endDate2JLabel.setText(" End Date : ");
        add(endDate2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 844, -1, -1));

        endDate2JTextField.setText(" ");
        add(endDate2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1246, 841, 201, -1));

        degree3JLabel.setText("Degree 3 : ");
        add(degree3JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 899, -1, -1));

        degree3JTextField.setText(" ");
        add(degree3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 896, 227, -1));

        startDate3JLabel.setText("Start Date :");
        add(startDate3JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 899, -1, -1));

        startDate3JTextField.setText(" ");
        startDate3JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDate3JTextFieldActionPerformed(evt);
            }
        });
        add(startDate3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 896, 209, -1));

        endDate3JLabel.setText(" End Date : ");
        add(endDate3JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 899, -1, -1));
        add(endDate3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1246, 896, 201, -1));

        workExperienceJLabel.setText("years of work experience : ");
        add(workExperienceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 966, -1, -1));

        yearsJTextField.setText(" ");
        add(yearsJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 960, 104, -1));

        skillsJLabel.setText("Which of the following skills have you worked on ?");
        add(skillsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1030, -1, -1));

        javaJCheckBox.setText("Java");
        javaJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaJCheckBoxActionPerformed(evt);
            }
        });
        add(javaJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 1075, -1, -1));

        webDesignJCheckBox.setText("Web Design");
        add(webDesignJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 1075, -1, -1));

        dotnetJCheckBox.setText("Dotnet");
        add(dotnetJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 1075, -1, -1));

        databaseJCheckBox.setText("Database");
        add(databaseJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 1075, -1, -1));

        bigDataJCheckBox.setText("Big data ");
        add(bigDataJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 1134, -1, -1));

        cJCheckBox.setText("C#");
        add(cJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1134, -1, -1));

        certificationsJLabel.setText("Certifications:");
        add(certificationsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 1233, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1460, 1447, 10));

        browseJButton.setText("Browse");
        browseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseJButtonActionPerformed(evt);
            }
        });
        add(browseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 1559, -1, -1));

        ImageheadingJLabel.setText("Please browse your image to add it in the resume : ");
        add(ImageheadingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 1498, -1, -1));

        emailJLabel.setText("Email ID :");
        add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 427, -1, -1));

        emailJTextField.setText(" ");
        add(emailJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 424, 328, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 1628, -1, -1));

        certifictionsJTextArea.setColumns(20);
        certifictionsJTextArea.setRows(5);
        jScrollPane1.setViewportView(certifictionsJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 1199, 1175, 179));

        objectiveJTextArea.setColumns(20);
        objectiveJTextArea.setRows(5);
        jScrollPane2.setViewportView(objectiveJTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 491, 963, 204));

        browsePathJTextField.setText(" ");
        add(browsePathJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 1560, 469, -1));
        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1502, 2, 20, 1710));
    }// </editor-fold>//GEN-END:initComponents

    private void addressLine1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine1TextFieldActionPerformed

    private void startDate3JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDate3JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDate3JTextFieldActionPerformed

    private void javaJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaJCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_javaJCheckBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        resume.setFirstName(firstNameTextField.getText());
        resume.setLastName(lastNameTextField.getText());
        resume.setAddressLine1(addressLine1TextField.getText());
        resume.setAddressLine2(addressLine2JTextField.getText());
        resume.setCity(cityJTextField.getText());
        resume.setCountry(countryJTextField.getText());
        resume.setAffiliation(affiliationJTextField.getText());
        resume.setEmailID(emailJTextField.getText());
        resume.setCareerObjective(objectiveJTextArea.getText());
        resume.setEducationDegree1(degree1JTextField.getText());
        resume.setEducationDegree2(degree2JTextField.getText());
        resume.setEducationDegree3(degree3JTextField.getText());
        resume.setDegreeStartDate1(start1JTextField.getText());
        resume.setDegreeStartDate2(startDate2JTextField.getText());
        resume.setDegreeStartDate3(startDate3JTextField.getText());
        resume.setDegreeEndDate1(endDate1JTextField.getText());
        resume.setDegreeEndDate2(endDate2JTextField.getText());
        resume.setDegreeEndDate3(endDate3JTextField.getText());
        resume.setWorkExperience(yearsJTextField.getText());
        resume.setCertification(certifictionsJTextArea.getText());
        resume.setBrowseImagePath(browsePathJTextField.getText());
        
        
        JOptionPane.showMessageDialog(null,"Resume has been Created Successfully");
        
        JScrollPane scrPane = new JScrollPane(container);
    add(scrPane);
    scrPane.setLayout(new ScrollPaneLayout());
    init();

    add(initConnectors());

    setSize(800, 600);
    setLocationRelativeTo(null);
        
        
        
        
                
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void browseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseJButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser =new JFileChooser();
        fileChooser.showOpenDialog(null);
        File file= fileChooser.getSelectedFile();
        String filePath= file.getAbsolutePath();
        browsePathJTextField.setText(filePath);
        
        
        
    }//GEN-LAST:event_browseJButtonActionPerformed

    private void degree1JTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degree1JTextFieldKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_degree1JTextFieldKeyPressed

    //code to attach image
    
    

    
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageheadingJLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLine1JLabel;
    private javax.swing.JTextField addressLine1TextField;
    private javax.swing.JLabel addressLine2JLabel;
    private javax.swing.JTextField addressLine2JTextField;
    private javax.swing.JLabel affiliationJLabel;
    private javax.swing.JTextField affiliationJTextField;
    private javax.swing.JCheckBox bigDataJCheckBox;
    private javax.swing.JButton browseJButton;
    private javax.swing.JTextField browsePathJTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cJCheckBox;
    private javax.swing.JLabel certificationsJLabel;
    private javax.swing.JTextArea certifictionsJTextArea;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JLabel createJLabel;
    private javax.swing.JCheckBox databaseJCheckBox;
    private javax.swing.JLabel degree1JLabel;
    private javax.swing.JTextField degree1JTextField;
    private javax.swing.JLabel degree2JLabel;
    private javax.swing.JTextField degree2JTextField;
    private javax.swing.JLabel degree3JLabel;
    private javax.swing.JTextField degree3JTextField;
    private javax.swing.JCheckBox dotnetJCheckBox;
    private javax.swing.JLabel educationHeadingJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JTextField endDate1JTextField;
    private javax.swing.JLabel endDate2JLabel;
    private javax.swing.JTextField endDate2JTextField;
    private javax.swing.JLabel endDate3JLabel;
    private javax.swing.JTextField endDate3JTextField;
    private javax.swing.JLabel endDte1JLabel;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox javaJCheckBox;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel nameHeadingJLabel;
    private javax.swing.JTextArea objectiveJTextArea;
    private javax.swing.JLabel objectiveStatementJLabel;
    private javax.swing.JLabel skillsJLabel;
    private javax.swing.JTextField start1JTextField;
    private javax.swing.JLabel startDate1JLabel;
    private javax.swing.JLabel startDate2JLabel;
    private javax.swing.JTextField startDate2JTextField;
    private javax.swing.JLabel startDate3JLabel;
    private javax.swing.JTextField startDate3JTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox webDesignJCheckBox;
    private javax.swing.JLabel workExperienceJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
