/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Career.Resume;
import java.awt.Image;
import javax.swing.ImageIcon;



/**
 *
 * @author sneha
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJPanel
     */
    
 
    
    public ViewJPanel(Resume resume) {
        initComponents();
        displayResume(resume);
      
    }

    private void displayResume(Resume resume)
        {
        
       firstNameJLabel.setText(resume.getFirstName());
       lastNameJLabel.setText(resume.getLastName());
       addressLine1JLabel.setText(resume.getAddressLine1());
       addressLine2JLabel.setText(resume.getAddressLine2());
       cityJLabel.setText(resume.getCity());
       countryJLabel.setText(resume.getCountry());
       affliationLabel.setText(resume.getAffiliation());
       emailJLabel.setText(resume.getEmailID());
       objectiveJLabel.setText(resume.getCareerObjective());
       degree1JTextField.setText(resume.getEducationDegree1());
       degree2JTextField.setText(resume.getEducationDegree2());
       degree3JTextField.setText(resume.getEducationDegree3());
       start1JTextField.setText(resume.getDegreeStartDate1());
       startDate2JTextField.setText(resume.getDegreeStartDate2());
       startDate3JTextField.setText(resume.getDegreeStartDate3());
       endDate1JTextField.setText(resume.getDegreeEndDate1());
       endDate2JTextField.setText(resume.getDegreeEndDate2());
       endDate3JTextField.setText(resume.getDegreeEndDate3());
       certificationListJLabel.setText(resume.getCertification());
       
       
       String imageFilePath  = resume.getBrowseImagePath();
ImageIcon image= new ImageIcon(imageFilePath);
Image resumeImage=image.getImage();
Image scaledImage= resumeImage.getScaledInstance(198,207, Image.SCALE_SMOOTH);
ImageIcon newImage= new ImageIcon(scaledImage);
pictureJLabel.setIcon(newImage);

              
       
        
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        addressLine1JLabel = new javax.swing.JLabel();
        addressLine2JLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        countryJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        careerObjectiveJLabel = new javax.swing.JLabel();
        objectiveJLabel = new javax.swing.JLabel();
        educationHeadingJLabel = new javax.swing.JLabel();
        degree1JLabel = new javax.swing.JLabel();
        degree1JTextField = new javax.swing.JTextField();
        degree2JLabel = new javax.swing.JLabel();
        degree2JTextField = new javax.swing.JTextField();
        startDate1JLabel = new javax.swing.JLabel();
        start1JTextField = new javax.swing.JTextField();
        startDate2JLabel = new javax.swing.JLabel();
        startDate2JTextField = new javax.swing.JTextField();
        endDate1JLabel = new javax.swing.JLabel();
        endDate1JTextField = new javax.swing.JTextField();
        endDate2JLabel = new javax.swing.JLabel();
        endDate2JTextField = new javax.swing.JTextField();
        degree3JLabel = new javax.swing.JLabel();
        degree3JTextField = new javax.swing.JTextField();
        startDate3JLabel = new javax.swing.JLabel();
        startDate3JTextField = new javax.swing.JTextField();
        endDate3JLabel = new javax.swing.JLabel();
        endDate3JTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        workExperienceJLabel = new javax.swing.JLabel();
        yearsJLabel = new javax.swing.JLabel();
        skillsHeaderJLabel = new javax.swing.JLabel();
        skillSetJLabel = new javax.swing.JLabel();
        certificaionsHeaderJLabel = new javax.swing.JLabel();
        certificationListJLabel = new javax.swing.JLabel();
        pictureJLabel = new javax.swing.JLabel();
        affiliationHeadingJLabel = new javax.swing.JLabel();
        affliationLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameJLabel.setText(" ");
        add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 37, 147, -1));

        lastNameJLabel.setText(" ");
        add(lastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 37, 127, -1));

        addressLine1JLabel.setText(" ");
        add(addressLine1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 98, 307, -1));

        addressLine2JLabel.setText(" ");
        add(addressLine2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 135, 307, -1));

        cityJLabel.setText(" ");
        add(cityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 184, 125, -1));

        countryJLabel.setText(" ");
        add(countryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 184, 184, -1));

        emailJLabel.setText(" ");
        add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 37, 446, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 251, 1355, 10));

        careerObjectiveJLabel.setText("Career Objective : ");
        add(careerObjectiveJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 331, -1, -1));

        objectiveJLabel.setText(" ");
        add(objectiveJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 297, 1065, 101));

        educationHeadingJLabel.setText("Education Details : ");
        add(educationHeadingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 460, -1, -1));

        degree1JLabel.setText("Degree 1 : ");
        add(degree1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 523, -1, -1));

        degree1JTextField.setText(" ");
        add(degree1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 520, 227, -1));

        degree2JLabel.setText("Degree 2 : ");
        add(degree2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 585, -1, -1));
        add(degree2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 582, 227, -1));

        startDate1JLabel.setText("Start Date :");
        add(startDate1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 523, -1, -1));

        start1JTextField.setText(" ");
        add(start1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 520, 209, -1));

        startDate2JLabel.setText("Start Date :");
        add(startDate2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 585, -1, -1));

        startDate2JTextField.setText(" ");
        add(startDate2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 582, 209, -1));

        endDate1JLabel.setText(" End Date : ");
        add(endDate1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 523, -1, -1));

        endDate1JTextField.setText(" ");
        add(endDate1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 520, 201, -1));

        endDate2JLabel.setText(" End Date : ");
        add(endDate2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 585, -1, -1));

        endDate2JTextField.setText(" ");
        add(endDate2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 582, 201, -1));

        degree3JLabel.setText("Degree 3 : ");
        add(degree3JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 642, -1, -1));

        degree3JTextField.setText(" ");
        degree3JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree3JTextFieldActionPerformed(evt);
            }
        });
        add(degree3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 639, 227, -1));

        startDate3JLabel.setText("Start Date :");
        add(startDate3JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 642, -1, -1));

        startDate3JTextField.setText(" ");
        startDate3JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDate3JTextFieldActionPerformed(evt);
            }
        });
        add(startDate3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 639, 209, -1));

        endDate3JLabel.setText(" End Date : ");
        add(endDate3JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 642, -1, -1));
        add(endDate3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 639, 201, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 447, 1164, -1));

        workExperienceJLabel.setText("Work Experience : ");
        add(workExperienceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 815, -1, -1));

        yearsJLabel.setText(" ");
        add(yearsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 815, 137, -1));

        skillsHeaderJLabel.setText("Skills : ");
        add(skillsHeaderJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 944, -1, -1));

        skillSetJLabel.setText(" ");
        add(skillSetJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 892, 1182, 136));

        certificaionsHeaderJLabel.setText("Certifications : ");
        add(certificaionsHeaderJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1094, -1, -1));

        certificationListJLabel.setText(" ");
        add(certificationListJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 1056, 1072, 109));
        add(pictureJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 198, 207));

        affiliationHeadingJLabel.setText("Affiliaion : ");
        add(affiliationHeadingJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 706, -1, -1));

        affliationLabel.setText(" ");
        add(affliationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 706, 335, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void startDate3JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDate3JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDate3JTextFieldActionPerformed

    private void degree3JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree3JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degree3JTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLine1JLabel;
    private javax.swing.JLabel addressLine2JLabel;
    private javax.swing.JLabel affiliationHeadingJLabel;
    private javax.swing.JLabel affliationLabel;
    private javax.swing.JLabel careerObjectiveJLabel;
    private javax.swing.JLabel certificaionsHeaderJLabel;
    private javax.swing.JLabel certificationListJLabel;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JLabel degree1JLabel;
    private javax.swing.JTextField degree1JTextField;
    private javax.swing.JLabel degree2JLabel;
    private javax.swing.JTextField degree2JTextField;
    private javax.swing.JLabel degree3JLabel;
    private javax.swing.JTextField degree3JTextField;
    private javax.swing.JLabel educationHeadingJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel endDate1JLabel;
    private javax.swing.JTextField endDate1JTextField;
    private javax.swing.JLabel endDate2JLabel;
    private javax.swing.JTextField endDate2JTextField;
    private javax.swing.JLabel endDate3JLabel;
    private javax.swing.JTextField endDate3JTextField;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JLabel objectiveJLabel;
    private javax.swing.JLabel pictureJLabel;
    private javax.swing.JLabel skillSetJLabel;
    private javax.swing.JLabel skillsHeaderJLabel;
    private javax.swing.JTextField start1JTextField;
    private javax.swing.JLabel startDate1JLabel;
    private javax.swing.JLabel startDate2JLabel;
    private javax.swing.JTextField startDate2JTextField;
    private javax.swing.JLabel startDate3JLabel;
    private javax.swing.JTextField startDate3JTextField;
    private javax.swing.JLabel workExperienceJLabel;
    private javax.swing.JLabel yearsJLabel;
    // End of variables declaration//GEN-END:variables
}
